Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vitor Henrique
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : WEndell Baresi
// Data atual  : 23/02/2022
Var
// Seção de Declarações das variáveis 
 n1 : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um número: ")
   leia(n1)
   
   escreva("Você digitou o número: ",n1)

Fimalgoritmo