Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Vitor Henrique
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Wendell Baresi
// Data atual  : 25/02/2022
Var
// Seção de Declarações das variáveis 
n1 : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite um numero ")
leia (n1)

escreval("Seu número é: ",n1)

Fimalgoritmo